### ISSUE TITLE
error with hostname and cache

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/uwhoisd#9]
Hello,

if we submit host.domain.tld uwhoisd tries to get the whois entry for this host, but when we scan for domain.tld is reuse the cache.
It should be nice to exclude the host and only scan the registered domain.

BR,

**Comment by Rafiot** [comment]
Fixed: https://github.com/Lookyloo/uwhoisd/commit/fc23392e4e861e6f2d7d491707fbf68c95b68a3f
